### Data cleaning Harry potter

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
# load in the data
characters = pd.read_csv('data/Characters.csv', sep=';')
potions = pd.read_csv('data/Potions.csv', sep=';')
spells = pd.read_csv('data/Spells.csv', sep=';')
master = pd.read_csv('data/harry_potter_master_data.csv')

### Data cleaning of the characters csv

In [2]:
characters.head()

,Id,Name,Gender,Job,House,Wand,Patronus,Species,Blood status,Hair colour,Eye colour,Loyalty,Skills,Birth,Death
0,1,Harry James Potter,Male,Student,Gryffindor,"11"" Holly phoenix feather",Stag,Human,Half-blood,Black,Bright green,Albus Dumbledore | Dumbledore's Army | Order o...,Parseltongue| Defence Against the Dark Arts | ...,31 July 1980,NaN
1,2,Ronald Bilius Weasley,Male,Student,Gryffindor,"12"" Ash unicorn tail hair",Jack Russell terrier,Human,Pure-blood,Red,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Wizard chess | Quidditch goalkeeping,1 March 1980,NaN
2,3,Hermione Jean Granger,Female,Student,Gryffindor,"10¾"" vine wood dragon heartstring",Otter,Human,Muggle-born,Brown,Brown,Dumbledore's Army | Order of the Phoenix | Hog...,Almost everything,"19 September, 1979",NaN
3,4,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,"15"" Elder Thestral tail hair core",Phoenix,Human,Half-blood,Silver| formerly auburn,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Considered by many to be one of the most power...,Late August 1881,"30 June, 1997"
4,5,Rubeus Hagrid,Male,Keeper of Keys and Grounds | Professor of Care...,Gryffindor,"16"" Oak unknown core",NaN,Half-Human/Half-Giant,Part-Human (Half-giant),Black,Black,Albus Dumbledore | Order of the Phoenix | Hogw...,Resistant to stunning spells| above average st...,6 December 1928,NaN

In [3]:
characters.info()

<class 'pandas.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            140 non-null    int64
 1   Name          140 non-null    str
 2   Gender        139 non-null    str
 3   Job           121 non-null    str
 4   House         101 non-null    str
 5   Wand          132 non-null    str
 6   Patronus      123 non-null    str
 7   Species       140 non-null    str
 8   Blood status  123 non-null    str
 9   Hair colour   123 non-null    str
 10  Eye colour    86 non-null     str
 11  Loyalty       89 non-null     str
 12  Skills        113 non-null    str
 13  Birth         127 non-null    str
 14  Death         42 non-null     str
dtypes: int64(1), str(14)
memory usage: 40.4 KB

#### Every column have the data type string, which seems okey knwoing how the data is formated in the csv file, maybe we will change some columns like birth and death to date.

In [4]:
characters.columns = characters.columns.str.strip().str.replace(' ', '_').str.lower() # make the column names more consistent and easier to work with
characters.head()

,id,name,gender,job,house,wand,patronus,species,blood_status,hair_colour,eye_colour,loyalty,skills,birth,death
0,1,Harry James Potter,Male,Student,Gryffindor,"11"" Holly phoenix feather",Stag,Human,Half-blood,Black,Bright green,Albus Dumbledore | Dumbledore's Army | Order o...,Parseltongue| Defence Against the Dark Arts | ...,31 July 1980,NaN
1,2,Ronald Bilius Weasley,Male,Student,Gryffindor,"12"" Ash unicorn tail hair",Jack Russell terrier,Human,Pure-blood,Red,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Wizard chess | Quidditch goalkeeping,1 March 1980,NaN
2,3,Hermione Jean Granger,Female,Student,Gryffindor,"10¾"" vine wood dragon heartstring",Otter,Human,Muggle-born,Brown,Brown,Dumbledore's Army | Order of the Phoenix | Hog...,Almost everything,"19 September, 1979",NaN
3,4,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,"15"" Elder Thestral tail hair core",Phoenix,Human,Half-blood,Silver| formerly auburn,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Considered by many to be one of the most power...,Late August 1881,"30 June, 1997"
4,5,Rubeus Hagrid,Male,Keeper of Keys and Grounds | Professor of Care...,Gryffindor,"16"" Oak unknown core",NaN,Half-Human/Half-Giant,Part-Human (Half-giant),Black,Black,Albus Dumbledore | Order of the Phoenix | Hogw...,Resistant to stunning spells| above average st...,6 December 1928,NaN

In [5]:
characters.describe(include="all") # get a summary of the data, including counts, unique values, and basic statistics.

,id,name,gender,job,house,wand,patronus,species,blood_status,hair_colour,eye_colour,loyalty,skills,birth,death
count,140.0000,140,139,121,101,132,123,140,123,123,86,89,113,127,42
unique,NaN,140,2,65,6,29,19,10,15,36,25,19,94,112,25
top,NaN,Harry James Potter,Male,Student,Gryffindor,Unknown,Unknown,Human,Pure-blood or half-blood,Black,Brown,Order of the Phoenix,Chaser,Pre 976,"2 May, 1998"
freq,NaN,1,90,52,38,104,75,105,38,25,16,16,7,4,9
mean,70.5000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,40.5586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,35.7500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,70.5000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,105.2500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,140.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
characters.shape # check the number of rows and columns in the dataset

(140, 15)

In [7]:
characters.columns # check the column names to identify any potential issues with naming conventions or inconsistencies.

Index(['id', 'name', 'gender', 'job', 'house', 'wand', 'patronus', 'species',
       'blood_status', 'hair_colour', 'eye_colour', 'loyalty', 'skills',
       'birth', 'death'],
      dtype='str')

In [8]:
characters.duplicated().sum() # check for duplicate rows in the dataset

np.int64(0)

In [9]:
print(characters["house"].value_counts()) # check the distribution of values in the "house" column to identify any potential issues with data quality or consistency.
print(characters["gender"].value_counts()) # check the distribution of values in the "gender" column to identify any potential issues with data quality or consistency.
print(characters["species"].value_counts()) # check the distribution of values in the "species" column to identify any potential issues with data quality or consistency.

house
Gryffindor                      38
Slytherin                       28
Ravenclaw                       18
Hufflepuff                      13
Beauxbatons Academy of Magic     3
Durmstrang Institute             1
Name: count, dtype: int64
gender
Male      90
Female    49
Name: count, dtype: int64
species
Human                      105
Human                       19
Ghost                        6
Half-Human/Half-Giant        2
Werewolf                     2
House elf                    2
Human (Werewolf traits)      1
Human(goblin ancestry)       1
Centaur                      1
Human (Metamorphmagus)       1
Name: count, dtype: int64

In [10]:
characters.isnull().sum() # check for missing values in each column to identify any potential issues with data completeness or quality.

id               0
name             0
gender           1
job             19
house           39
wand             8
patronus        17
species          0
blood_status    17
hair_colour     17
eye_colour      54
loyalty         51
skills          27
birth           13
death           98
dtype: int64

In [11]:
characters["id"].is_unique # check if the "id" column contains unique values to ensure that it can be used as a primary key for the dataset.

True

In [12]:
characters = characters.drop(columns=['hair_colour', 'eye_colour', 'wand']) # drop columns with too many missing values and not relevant us
characters.head()

,id,name,gender,job,house,patronus,species,blood_status,loyalty,skills,birth,death
0,1,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood,Albus Dumbledore | Dumbledore's Army | Order o...,Parseltongue| Defence Against the Dark Arts | ...,31 July 1980,NaN
1,2,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood,Dumbledore's Army | Order of the Phoenix | Hog...,Wizard chess | Quidditch goalkeeping,1 March 1980,NaN
2,3,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born,Dumbledore's Army | Order of the Phoenix | Hog...,Almost everything,"19 September, 1979",NaN
3,4,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood,Dumbledore's Army | Order of the Phoenix | Hog...,Considered by many to be one of the most power...,Late August 1881,"30 June, 1997"
4,5,Rubeus Hagrid,Male,Keeper of Keys and Grounds | Professor of Care...,Gryffindor,NaN,Half-Human/Half-Giant,Part-Human (Half-giant),Albus Dumbledore | Order of the Phoenix | Hogw...,Resistant to stunning spells| above average st...,6 December 1928,NaN

### Data cleaning of the potions csv

In [13]:
potions.head()

,Name,Known ingredients,Effect,Characteristics,Difficulty level
0,Ageing Potion,"Newt spleens , Bananas",Ages drinker temporarily,Green,Advanced
1,Amortentia,NaN,Love Potion that causes a powerful infatuation...,"Mother-of-pearl sheen, Spiralling steam, Scent...",Advanced
2,Antidote to Veritaserum,NaN,Counters the effect of Veritaserum,NaN,NaN
3,Babbling Beverage,"Valerian sprigs, Aconite, Dittany",Causes the drinker to speak nonsense,NaN,NaN
4,Baruffio's Brain Elixir,"Leaping Toadstools, Frog Brains, Runespoor egg...",Allegedly increases one's brain power,Green in colour,NaN

In [14]:
potions.info()

<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               72 non-null     str
 1   Known ingredients  42 non-null     str
 2   Effect             68 non-null     str
 3   Characteristics    41 non-null     str
 4   Difficulty level   25 non-null     str
dtypes: str(5)
memory usage: 10.7 KB

In [15]:
potions.columns = potions.columns.str.strip().str.replace(' ', '_').str.lower() # make the column names more consistent and easier to work with
potions.head()

,name,known_ingredients,effect,characteristics,difficulty_level
0,Ageing Potion,"Newt spleens , Bananas",Ages drinker temporarily,Green,Advanced
1,Amortentia,NaN,Love Potion that causes a powerful infatuation...,"Mother-of-pearl sheen, Spiralling steam, Scent...",Advanced
2,Antidote to Veritaserum,NaN,Counters the effect of Veritaserum,NaN,NaN
3,Babbling Beverage,"Valerian sprigs, Aconite, Dittany",Causes the drinker to speak nonsense,NaN,NaN
4,Baruffio's Brain Elixir,"Leaping Toadstools, Frog Brains, Runespoor egg...",Allegedly increases one's brain power,Green in colour,NaN

In [16]:
potions.describe(include="all") # get a summary of the data, including counts, unique values, and basic statistics.

,name,known_ingredients,effect,characteristics,difficulty_level
count,72,42,68,41,25
unique,72,41,65,37,7
top,Ageing Potion,"Scurvy grass, Lovage, Sneezewort",Causes the drinker to become infatuated with t...,Green,Advanced
freq,1,2,4,2,14

In [17]:
potions.shape # check the number of rows and columns in the dataset

(72, 5)

In [18]:
potions.columns # check the column names to identify any potential issues with naming conventions or inconsistencies.

Index(['name', 'known_ingredients', 'effect', 'characteristics',
       'difficulty_level'],
      dtype='str')

In [19]:
potions.duplicated().sum() # check for duplicate rows in the dataset

np.int64(0)

In [20]:
potions.isnull().sum() # check for missing values in each column to identify any potential issues with data completeness or quality.

name                  0
known_ingredients    30
effect                4
characteristics      31
difficulty_level     47
dtype: int64

In [21]:
potions["name"].is_unique # check if the "name" column contains unique values to ensure that it can be used as a primary key for the dataset.

True

In [22]:
potions = potions.drop(columns=['difficulty_level']) # drop column with too many missing values and not relevant for us
potions.head()

,name,known_ingredients,effect,characteristics
0,Ageing Potion,"Newt spleens , Bananas",Ages drinker temporarily,Green
1,Amortentia,NaN,Love Potion that causes a powerful infatuation...,"Mother-of-pearl sheen, Spiralling steam, Scent..."
2,Antidote to Veritaserum,NaN,Counters the effect of Veritaserum,NaN
3,Babbling Beverage,"Valerian sprigs, Aconite, Dittany",Causes the drinker to speak nonsense,NaN
4,Baruffio's Brain Elixir,"Leaping Toadstools, Frog Brains, Runespoor egg...",Allegedly increases one's brain power,Green in colour

### Data cleaning of the spells csv

In [23]:
spells.head()

,Name,Incantation,Type,Effect,Light
0,Summoning Charm,Accio,Charm,Summons an object,NaN
1,Age Line,Unknown,Charm,Prevents people above or below a certain age f...,Blue
2,Water-Making Spell,Aguamenti,"Charm, Conjuration",Conjures water,Icy blue
3,Launch an object up into the air,Alarte Ascendare,Charm,Rockets target upward,Red
4,Albus Dumbledore's Forceful Spell,Unknown,Spell,Great Force,NaN

In [24]:
spells.info()

<class 'pandas.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         301 non-null    str
 1   Incantation  294 non-null    str
 2   Type         301 non-null    str
 3   Effect       301 non-null    str
 4   Light        146 non-null    str
dtypes: str(5)
memory usage: 30.1 KB

In [25]:
spells.columns = spells.columns.str.strip().str.lower() # make the column names more consistent and easier to work with
spells.head()

,name,incantation,type,effect,light
0,Summoning Charm,Accio,Charm,Summons an object,NaN
1,Age Line,Unknown,Charm,Prevents people above or below a certain age f...,Blue
2,Water-Making Spell,Aguamenti,"Charm, Conjuration",Conjures water,Icy blue
3,Launch an object up into the air,Alarte Ascendare,Charm,Rockets target upward,Red
4,Albus Dumbledore's Forceful Spell,Unknown,Spell,Great Force,NaN

In [26]:
spells.describe(include="all") # get a summary of the data, including counts, unique values, and basic statistics.

                   name incantation   type               effect light
count               301         294    301                  301   146
unique              301         184     35                  296    45
top     Summoning Charm     Unknown  Charm  Jet of white sparks  Blue
freq                  1         108    148                    2    30

In [27]:
spells.columns # check the column names to identify any potential issues with naming conventions or inconsistencies.

Index(['name', 'incantation', 'type', 'effect', 'light'], dtype='str')

In [28]:
spells.shape # check the number of rows and columns in the dataset

(301, 5)

In [29]:
spells.duplicated().sum() # check for duplicate rows in the dataset

np.int64(0)

In [30]:
spells.isnull().sum() # check for missing values in each column to identify any potential issues with data completeness or quality.

name             0
incantation      7
type             0
effect           0
light          155
dtype: int64

In [31]:
spells["name"].is_unique # check if the "name" column contains unique values to ensure that it can be used as a primary key for the dataset.

True

In [32]:
spells = spells.drop(columns=['light']) # drop columns with too many missing values and not relevant for us
spells.head()

,name,incantation,type,effect
0,Summoning Charm,Accio,Charm,Summons an object
1,Age Line,Unknown,Charm,Prevents people above or below a certain age f...
2,Water-Making Spell,Aguamenti,"Charm, Conjuration",Conjures water
3,Launch an object up into the air,Alarte Ascendare,Charm,Rockets target upward
4,Albus Dumbledore's Forceful Spell,Unknown,Spell,Great Force

### Data cleaning of the master csv

In [33]:
master.head()

,entity_type,name,slug,alias_names,animagus,blood_status,boggart,born,died,eye_color,...,manufacturers,side_effects,time,author,cover,dedication,pages,release_date,summary,title
0,characters,1980s Hogwarts Gobstones Tournament champion,1980s-hogwarts-gobstones-tournament-champion,[],NaN,Pure-blood or half-blood,NaN,Between 1 September 1971 and 31 August 1972,"c. 1986 or after (aged 14 at least), Great Lak...",Green,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,characters,1980s Hogwarts Gobstones Tournament champion's...,1980s-hogwarts-gobstones-tournament-champion-s...,[],NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,characters,1992 Gryffindor vs Slytherin Quidditch match s...,1992-gryffindor-vs-slytherin-quidditch-match-s...,[],NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,characters,1996 Gryffindor Quidditch Keeper trials specta...,1996-gryffindor-quidditch-keeper-trials-specta...,[],NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,characters,2-Headed Baby,2-headed-baby,[],NaN,NaN,NaN,Before 1927,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 5907 entries, 0 to 5906
Data columns (total 48 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   entity_type      5907 non-null   str
 1   name             5900 non-null   str
 2   slug             5907 non-null   str
 3   alias_names      5387 non-null   str
 4   animagus         29 non-null     str
 5   blood_status     1411 non-null   str
 6   boggart          104 non-null    str
 7   born             3066 non-null   str
 8   died             873 non-null    str
 9   eye_color        1375 non-null   str
 10  family_members   5387 non-null   str
 11  gender           4722 non-null   str
 12  hair_color       1804 non-null   str
 13  height           70 non-null     str
 14  house            1088 non-null   str
 15  image            3272 non-null   str
 16  jobs             5387 non-null   str
 17  marital_status   515 non-null    str
 18  nationality      2923 non-null   str
 19  patronus         119 non-null    str
 20  romances         5387 non-null   str
 21  skin_color       1883 non-null   str
 22  species          5282 non-null   str
 23  titles           5387 non-null   str
 24  wands            5387 non-null   str
 25  weight           25 non-null     str
 26  wiki             5907 non-null   str
 27  entity_id        5907 non-null   str
 28  category         340 non-null    str
 29  creator          32 non-null     str
 30  effect           486 non-null    str
 31  hand             89 non-null     str
 32  incantation      213 non-null    str
 33  light            174 non-null    str
 34  characteristics  129 non-null    str
 35  difficulty       67 non-null     str
 36  inventors        32 non-null     str
 37  ingredients      106 non-null    str
 38  manufacturers    15 non-null     str
 39  side_effects     23 non-null     str
 40  time             18 non-null     str
 41  author           7 non-null      str
 42  cover            7 non-null      str
 43  dedication       7 non-null      str
 44  pages            7 non-null      float64
 45  release_date     7 non-null      str
 46  summary          7 non-null      str
 47  title            7 non-null      str
dtypes: float64(1), str(47)
memory usage: 3.9 MB

In [35]:
master.describe(include="all") #get a summary of the data, including counts, unique values, and basic statistics.

,entity_type,name,slug,alias_names,animagus,blood_status,boggart,born,died,eye_color,...,manufacturers,side_effects,time,author,cover,dedication,pages,release_date,summary,title
count,5907,5900,5907,5387,29,1411,104,3066,873,1375,...,15,23,18,7,7,7,7.000000,7,7,7
unique,4,5695,5907,282,29,88,31,1385,581,84,...,14,23,16,1,7,7,NaN,7,7,7
top,characters,Unidentified Death Eater,1980s-hogwarts-gobstones-tournament-champion,[],Gerbil,Muggle,Lord Voldemort,31 August 1982 or earlier,Before 1890,Brown,...,Hogwarts Apothecary Dept.,Varies,Six hours,J. K. Rowling,https://www.wizardingworld.com/images/products...,"For Jessica, who loves stories, for Anne, who ...",NaN,1997-06-26,Harry Potter has never even heard of Hogwarts ...,Harry Potter and the Philosopher's Stone
freq,5387,15,1,5105,1,362,68,281,35,470,...,2,1,2,7,1,1,NaN,1,1,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,487.142857,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,217.509715,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,223.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,284.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,607.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,623.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,766.000000,NaN,NaN,NaN

In [36]:
master.columns # check the column names to identify any potential issues with naming conventions or inconsistencies.

Index(['entity_type', 'name', 'slug', 'alias_names', 'animagus',
       'blood_status', 'boggart', 'born', 'died', 'eye_color',
       'family_members', 'gender', 'hair_color', 'height', 'house', 'image',
       'jobs', 'marital_status', 'nationality', 'patronus', 'romances',
       'skin_color', 'species', 'titles', 'wands', 'weight', 'wiki',
       'entity_id', 'category', 'creator', 'effect', 'hand', 'incantation',
       'light', 'characteristics', 'difficulty', 'inventors', 'ingredients',
       'manufacturers', 'side_effects', 'time', 'author', 'cover',
       'dedication', 'pages', 'release_date', 'summary', 'title'],
      dtype='str')

#### The columns about the book like author, cover doesn't seem relevant for the purpose. columns like wiki, wand, hair-and eye color, image, height, family_members doesn't seem relevant.

In [37]:
master.shape # check the number of rows and columns in the dataset

(5907, 48)

In [38]:
master.duplicated().sum() # check for duplicate rows in the dataset

np.int64(0)

In [39]:
master.isnull().sum() # check for missing values in each column to identify any potential issues with data completeness or quality.

entity_type           0
name                  7
slug                  0
alias_names         520
animagus           5878
blood_status       4496
boggart            5803
born               2841
died               5034
eye_color          4532
family_members      520
gender             1185
hair_color         4103
height             5837
house              4819
image              2635
jobs                520
marital_status     5392
nationality        2984
patronus           5788
romances            520
skin_color         4024
species             625
titles              520
wands               520
weight             5882
wiki                  0
entity_id             0
category           5567
creator            5875
effect             5421
hand               5818
incantation        5694
light              5733
characteristics    5778
difficulty         5840
inventors          5875
ingredients        5801
manufacturers      5892
side_effects       5884
time               5889
author             5900
cover              5900
dedication         5900
pages              5900
release_date       5900
summary            5900
title              5900
dtype: int64

In [40]:
master = master.drop(columns=['hair_color', 'eye_color', 'born', 'died', 'family_members', 'height', 
                              'image', 'marital_status', 'nationality', 'skin_color', 'wands', 'slug', 'wiki',
                              'author', 'cover', 'dedication', 'pages', 'release_date', 
                              'summary']) # drop columns with too many missing values and not relevant for us

master.head()

,entity_type,name,alias_names,animagus,blood_status,boggart,gender,house,jobs,patronus,...,incantation,light,characteristics,difficulty,inventors,ingredients,manufacturers,side_effects,time,title
0,characters,1980s Hogwarts Gobstones Tournament champion,[],NaN,Pure-blood or half-blood,NaN,Male,Hufflepuff,[],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,characters,1980s Hogwarts Gobstones Tournament champion's...,[],NaN,NaN,NaN,"Male, female",NaN,[],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,characters,1992 Gryffindor vs Slytherin Quidditch match s...,[],NaN,NaN,NaN,NaN,NaN,[],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,characters,1996 Gryffindor Quidditch Keeper trials specta...,[],NaN,NaN,NaN,NaN,NaN,[],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,characters,2-Headed Baby,[],NaN,NaN,NaN,Male (most likely),NaN,['Circus performers'],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
master = master.dropna(subset=['name']) # drop rows with missing values in the "name" column, as this is a key identifier for the characters and is necessary for analysis.

In [42]:
master = master.dropna(thresh=5) # drop rows with less than 5 non-missing values, as these rows may not contain enough information to be useful for analysis.

In [43]:
master.info()

<class 'pandas.DataFrame'>
Index: 5875 entries, 0 to 5899
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   entity_type      5875 non-null   str
 1   name             5875 non-null   str
 2   alias_names      5387 non-null   str
 3   animagus         29 non-null     str
 4   blood_status     1411 non-null   str
 5   boggart          104 non-null    str
 6   gender           4722 non-null   str
 7   house            1088 non-null   str
 8   jobs             5387 non-null   str
 9   patronus         119 non-null    str
 10  romances         5387 non-null   str
 11  species          5282 non-null   str
 12  titles           5387 non-null   str
 13  weight           25 non-null     str
 14  entity_id        5875 non-null   str
 15  category         340 non-null    str
 16  creator          32 non-null     str
 17  effect           476 non-null    str
 18  hand             89 non-null     str
 19  incantation      209 non-null    str
 20  light            174 non-null    str
 21  characteristics  124 non-null    str
 22  difficulty       67 non-null     str
 23  inventors        32 non-null     str
 24  ingredients      104 non-null    str
 25  manufacturers    14 non-null     str
 26  side_effects     23 non-null     str
 27  time             18 non-null     str
 28  title            0 non-null      str
dtypes: str(29)
memory usage: 2.0 MB

In [44]:
master.shape # check the number of rows and columns in the dataset

(5875, 29)

In [45]:
# Load the cleaned data into new CSV files for future use
characters.to_csv('data/cleaned_characters.csv', index=False)
potions.to_csv('data/cleaned_potions.csv', index=False)
spells.to_csv('data/cleaned_spells.csv', index=False)
master.to_csv('data/cleaned_master.csv', index=False)