### Data cleaning Harry potter

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
# load in the data
characters = pd.read_csv('data/Characters.csv', sep=';')
potions = pd.read_csv('data/Potions.csv', sep=';')
spells = pd.read_csv('data/Spells.csv', sep=';')

### Data cleaning of the characters csv

In [3]:
characters.head()

,Id,Name,Gender,Job,House,Wand,Patronus,Species,Blood status,Hair colour,Eye colour,Loyalty,Skills,Birth,Death
0,1,Harry James Potter,Male,Student,Gryffindor,"11"" Holly phoenix feather",Stag,Human,Half-blood,Black,Bright green,Albus Dumbledore | Dumbledore's Army | Order o...,Parseltongue| Defence Against the Dark Arts | ...,31 July 1980,NaN
1,2,Ronald Bilius Weasley,Male,Student,Gryffindor,"12"" Ash unicorn tail hair",Jack Russell terrier,Human,Pure-blood,Red,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Wizard chess | Quidditch goalkeeping,1 March 1980,NaN
2,3,Hermione Jean Granger,Female,Student,Gryffindor,"10¾"" vine wood dragon heartstring",Otter,Human,Muggle-born,Brown,Brown,Dumbledore's Army | Order of the Phoenix | Hog...,Almost everything,"19 September, 1979",NaN
3,4,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,"15"" Elder Thestral tail hair core",Phoenix,Human,Half-blood,Silver| formerly auburn,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Considered by many to be one of the most power...,Late August 1881,"30 June, 1997"
4,5,Rubeus Hagrid,Male,Keeper of Keys and Grounds | Professor of Care...,Gryffindor,"16"" Oak unknown core",NaN,Half-Human/Half-Giant,Part-Human (Half-giant),Black,Black,Albus Dumbledore | Order of the Phoenix | Hogw...,Resistant to stunning spells| above average st...,6 December 1928,NaN

In [3]:
characters.info()

<class 'pandas.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            140 non-null    int64
 1   Name          140 non-null    str
 2   Gender        139 non-null    str
 3   Job           121 non-null    str
 4   House         101 non-null    str
 5   Wand          132 non-null    str
 6   Patronus      123 non-null    str
 7   Species       140 non-null    str
 8   Blood status  123 non-null    str
 9   Hair colour   123 non-null    str
 10  Eye colour    86 non-null     str
 11  Loyalty       89 non-null     str
 12  Skills        113 non-null    str
 13  Birth         127 non-null    str
 14  Death         42 non-null     str
dtypes: int64(1), str(14)
memory usage: 16.5 KB

Alla är har datatypen strings,

In [4]:
characters.tail()

,Id,Name,Gender,Job,House,Wand,Patronus,Species,Blood status,Hair colour,Eye colour,Loyalty,Skills,Birth,Death
135,136,Wilhelmina Grubbly-Plank,Female,Substitute professor of Care of Magical Creatu...,NaN,Unknown,Non-corporeal,Human,NaN,Grey,NaN,Hogwarts School of Witchcraft and Wizardry,NaN,NaN,NaN
136,137,Fenrir Greyback,Male,NaN,NaN,Unknown,NaN,Werewolf,NaN,Grey,NaN,Lord Voldemort | Death Eaters,Physical combat,Pre 1945,NaN
137,138,Gellert Grindelwald,Male,Revolutionary leader(c. 1920s[6] – 1945),NaN,"15"", Elder, Thestral tail hair core",NaN,Human,Pure-blood or half-blood,Blond,Blue,Gellert Grindelwald's Acolytes,Duelling,1883,"March, 1998"
138,139,Dobby,Male,"Malfoy family's house-elf (? - 1993),\nHogwart...",NaN,NaN,NaN,House elf,NaN,Green,NaN,NaN,"A type of magic specific to house-elves, perfo...",28 June,"Late March, 1998"
139,140,Kreacher,Male,"\nBlack family's house-elf (?-1996), \nHarry P...",NaN,NaN,NaN,House elf,NaN,White,NaN,NaN,Magic performed without a wand which includes ...,NaN,NaN

In [5]:
characters.columns = characters.columns.str.strip().str.replace(' ', '_').str.lower() # make the column names more consistent and easier to work with
characters.head()

,id,name,gender,job,house,wand,patronus,species,blood_status,hair_colour,eye_colour,loyalty,skills,birth,death
0,1,Harry James Potter,Male,Student,Gryffindor,"11"" Holly phoenix feather",Stag,Human,Half-blood,Black,Bright green,Albus Dumbledore | Dumbledore's Army | Order o...,Parseltongue| Defence Against the Dark Arts | ...,31 July 1980,NaN
1,2,Ronald Bilius Weasley,Male,Student,Gryffindor,"12"" Ash unicorn tail hair",Jack Russell terrier,Human,Pure-blood,Red,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Wizard chess | Quidditch goalkeeping,1 March 1980,NaN
2,3,Hermione Jean Granger,Female,Student,Gryffindor,"10¾"" vine wood dragon heartstring",Otter,Human,Muggle-born,Brown,Brown,Dumbledore's Army | Order of the Phoenix | Hog...,Almost everything,"19 September, 1979",NaN
3,4,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,"15"" Elder Thestral tail hair core",Phoenix,Human,Half-blood,Silver| formerly auburn,Blue,Dumbledore's Army | Order of the Phoenix | Hog...,Considered by many to be one of the most power...,Late August 1881,"30 June, 1997"
4,5,Rubeus Hagrid,Male,Keeper of Keys and Grounds | Professor of Care...,Gryffindor,"16"" Oak unknown core",NaN,Half-Human/Half-Giant,Part-Human (Half-giant),Black,Black,Albus Dumbledore | Order of the Phoenix | Hogw...,Resistant to stunning spells| above average st...,6 December 1928,NaN

In [6]:
characters.value_counts()

id  name                                     gender  job                                          house       wand                               patronus           species   blood_status  hair_colour                    eye_colour  loyalty                                                                                skills                                                                 birth                              death
4   Albus Percival Wulfric Brian Dumbledore  Male    Headmaster                                   Gryffindor  15" Elder Thestral tail hair core  Phoenix            Human     Half-blood    Silver| formerly auburn        Blue        Dumbledore's Army | Order of the Phoenix | Hogwarts School of Witchcraft and Wizardry  Considered by many to be one of the most powerful wizards of his time  Late August 1881                   30 June, 1997     1
7   Fred Weasley                             Male    Student                                      Gryffindor  Unknown                            Unknown            Human     Pure-blood    Red                            Brown       Dumbledore's Army | Order of the Phoenix | Hogwarts School of Witchcraft and Wizardry  Beater                                                                 1 April, 1978                      2 May, 1998       1
15  Remus John Lupin                         Male    Professor of Defence Against the Dark Arts   Gryffindor  10¼" Cypress unicorn hair          Wolf               Werewolf  Half-blood    Light brown flecked with grey  Green       Order of the Phoenix                                                                   Exceptionally gifted in Defence Against the Dark Arts                  10 March, 1960                     2 May, 1998       1
25  Lavender Brown                           Female  Student                                      Gryffindor  Unknown                            Unknown            Human     Pure-blood    Blond                          Blue        Dumbledore's Army |Hogwarts School of Witchcraft and Wizardry                          Divination                                                              1 September 1979- 31 August 1980  2 May, 1998       1
81  Nymphadora Tonks                         Female  Auror                                        Hufflepuff  Unknown                            Jack rabbit, Wolf  Human     Half-blood    Variable                       Variable    Ministry of Magic | Order of the Phoenix                                               Talented Auror, Metamorphmagus                                          1 September 1972- 31 August 1973  2 May, 1998       1
Name: count, dtype: int64

In [7]:
characters.isnull().sum()

id               0
name             0
gender           1
job             19
house           39
wand             8
patronus        17
species          0
blood_status    17
hair_colour     17
eye_colour      54
loyalty         51
skills          27
birth           13
death           98
dtype: int64

Drop columns that aren't relevant and have many missing values.

In [ ]:
characters = characters.drop(columns=['hair_colour', 'eye_colour', 'wand']) # drop columns with too many missing values and not relevant us
characters.head()

,id,name,gender,job,house,patronus,species,blood_status,loyalty,skills,birth,death
0,1,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood,Albus Dumbledore | Dumbledore's Army | Order o...,Parseltongue| Defence Against the Dark Arts | ...,31 July 1980,NaN
1,2,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood,Dumbledore's Army | Order of the Phoenix | Hog...,Wizard chess | Quidditch goalkeeping,1 March 1980,NaN
2,3,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born,Dumbledore's Army | Order of the Phoenix | Hog...,Almost everything,"19 September, 1979",NaN
3,4,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood,Dumbledore's Army | Order of the Phoenix | Hog...,Considered by many to be one of the most power...,Late August 1881,"30 June, 1997"
4,5,Rubeus Hagrid,Male,Keeper of Keys and Grounds | Professor of Care...,Gryffindor,NaN,Half-Human/Half-Giant,Part-Human (Half-giant),Albus Dumbledore | Order of the Phoenix | Hogw...,Resistant to stunning spells| above average st...,6 December 1928,NaN